# Baselines

In [16]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

### Carregamento e preparação dos dados

In [17]:
df_train = pd.read_csv("../../dados/treino.csv")
df_train["date"] = pd.to_datetime(df_train["date"])
df_train

           date  store_total  FOODS  HOBBIES
0    2011-01-29         4337   3239      556
1    2011-01-30         4155   3137      498
2    2011-01-31         2816   2008      415
3    2011-02-01         3051   2258      392
4    2011-02-02         2630   2032      268
...         ...          ...    ...      ...
1880 2016-03-23         3770   2554      454
1881 2016-03-24         3970   2681      474
1882 2016-03-25         4904   3421      446
1883 2016-03-26         6139   4251      610
1884 2016-03-27         4669   3366      369

[1885 rows x 4 columns]

In [18]:
df_val = pd.read_csv("../../dados/validacao.csv")
df_val["date"] = pd.to_datetime(df_val["date"])
df_val

         date  store_total  FOODS  HOBBIES
0  2016-03-28         3905   2480      535
1  2016-03-29         3788   2481      498
2  2016-03-30         3339   2135      465
3  2016-03-31         4076   2651      536
4  2016-04-01         4983   3132      743
5  2016-04-02         5877   3890      603
6  2016-04-03         6496   4226      790
7  2016-04-04         4812   3273      463
8  2016-04-05         4063   2711      545
9  2016-04-06         3964   2698      427
10 2016-04-07         3655   2450      394
11 2016-04-08         4719   3141      582
12 2016-04-09         6112   4073      571
13 2016-04-10         5969   4061      547
14 2016-04-11         4484   2876      620
15 2016-04-12         3579   2372      391
16 2016-04-13         3478   2341      415
17 2016-04-14         3637   2421      429
18 2016-04-15         3982   2706      401
19 2016-04-16         5437   3481      722
20 2016-04-17         5954   4004      655
21 2016-04-18         4345   2886      542
22 2016-04-19         3793   2488      495
23 2016-04-20         3722   2490      363
24 2016-04-21         3709   2533      410
25 2016-04-22         4387   2960      527
26 2016-04-23         5577   3655      670
27 2016-04-24         6113   4053      714

## Funções de cálculo de cada baseline

In [ ]:
def baseline_media(y, h):
    media = np.mean(y)
    return [media] * h

def baseline_naive(y, h):
    y_array = np.asarray(y)
    ultimo_valor = y_array[-1]
    return [ultimo_valor] * h

def baseline_sazonal(y, h, m=7):
    y_array = np.asarray(y)
    previsoes = []

    for i in range(h):
        posicao = -m + (i % m)
        previsoes.append(y_array[posicao])
        
    return previsoes

def baseline_drift(y, h):
    y_array = np.asarray(y)
    T = len(y_array)
    y_T = y_array[-1]
    y_1 = y_array[0]
    
    C = (y_T - y_1) / (T - 1)
    
    previsoes = [y_T + (i + 1) * C for i in range(h)]
    return previsoes